// mentolder-web/src/components/CallToAction.tsx
import { Link } from 'react-router-dom';

interface CallToActionProps {
  eyebrow?: string;
  title?: string;
  titleEmphasis?: string;
  subtitle?: string;
  primaryText?: string;
  primaryHref?: string;
  secondaryText?: string;
  secondaryHref?: string;
}

export function CallToAction({
  eyebrow = 'Bereit?',
  title = 'Lassen Sie uns',
  titleEmphasis = 'in 30 Minuten herausfinden, ob es passt.',
  subtitle = 'Ein kostenloses Erstgespräch — unverbindlich, auf Augenhöhe und ohne Verkaufsdruck.',
  primaryText = 'Termin vereinbaren',
  primaryHref = '/kontakt',
  secondaryText = '',
  secondaryHref = '',
}: CallToActionProps) {
  return (
    <section
      className="py-[130px] border-t border-line relative overflow-hidden"
      aria-labelledby="cta-heading"
    >
      <div
        className="absolute inset-0 pointer-events-none"
        aria-hidden="true"
        style={{
          background:
            'radial-gradient(ellipse at 50% 100%, oklch(0.80 0.09 75 / .22), transparent 60%)',
        }}
      />
      <div className="max-w-[760px] mx-auto px-10 text-center relative z-[1] max-md:px-[22px]">
        <p className="font-mono text-[11px] tracking-[0.18em] uppercase text-brass inline-flex items-center gap-2.5 m-0 mb-4">
          <span aria-hidden="true" className="inline-block w-[22px] h-px bg-current opacity-80" />
          {eyebrow}
        </p>
        <h2
          id="cta-heading"
          className="font-serif font-normal text-fg leading-[1.1] m-0"
          style={{
            fontSize: 'clamp(28px, 3.6vw, 48px)',
            letterSpacing: '-0.02em',
          }}
        >
          {title}
          {titleEmphasis && (
            <>
              {' '}
              <em>{titleEmphasis}</em>
            </>
          )}
        </h2>
        <p className="text-[18px] leading-[1.6] text-fg-soft mt-5 mb-9 max-w-[52ch] mx-auto">
          {subtitle}
        </p>
        <div className="flex flex-wrap justify-center gap-[14px]" role="group" aria-label="Aktionen">
          <Link to={primaryHref} className="btn-primary">
            {primaryText}
            <svg
              viewBox="0 0 14 14"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              aria-hidden="true"
              className="w-[14px] h-[14px]"
            >
              <path d="M2 7h10M8 3l4 4-4 4" />
            </svg>
          </Link>
          {secondaryText && (
            <a href={secondaryHref || '#'} className="btn-ghost">
              {secondaryText}
            </a>
          )}
        </div>
      </div>

      <style>{`
        .btn-primary, .btn-ghost {
          display: inline-flex; align-items: center; gap: 10px;
          padding: 14px 22px; border-radius: 999px;
          font-family: var(--sans); font-size: 14px; font-weight: 600;
          text-decoration: none;
          transition: transform .2s ease, background .2s ease, border-color .2s ease, color .2s ease;
        }
        .btn-primary { background: var(--brass); color: var(--ink-900); }
        .btn-primary:hover { background: var(--brass-2); transform: translateY(-1px); box-shadow: 0 0 28px oklch(0.80 0.09 75 / 0.45); }
        .btn-ghost { color: var(--fg); border: 1px solid var(--line-2); background: transparent; }
        .btn-ghost:hover { border-color: var(--brass); color: var(--brass); }
        h2 em { font-style: italic; font-weight: 400; color: var(--brass-2); }
      `}</style>
    </section>
  );
}

// components/website/src/components/CallToAction.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { t, type Locale } from '../i18n/index';

  interface Props {
    locale?: Locale;
    eyebrow?: string;
    title?: string;
    titleEmphasis?: string;
    subtitle?: string;
    primaryText?: string;
    primaryHref?: string;
    secondaryText?: string;
    secondaryHref?: string;
  }

  let {
    locale = 'de',
    eyebrow,
    title,
    titleEmphasis,
    subtitle,
    primaryText,
    primaryHref = '/kontakt',
    secondaryText = '',
    secondaryHref = '',
  }: Props = $props();

  const effectiveEyebrow = $derived(eyebrow ?? t(locale, 'cta.eyebrow'));
  const effectiveTitle = $derived(title ?? t(locale, 'cta.title'));
  const effectiveTitleEmphasis = $derived(titleEmphasis ?? t(locale, 'cta.title-emphasis'));
  const effectiveSubtitle = $derived(subtitle ?? t(locale, 'cta.subtitle'));
  const effectivePrimaryText = $derived(primaryText ?? t(locale, 'cta.primary'));

  let sectionEl = $state<HTMLElement | null>(null);

  onMount(() => {
    if (!sectionEl) return;
    if (typeof IntersectionObserver === 'undefined') {
      sectionEl.classList.add('reveal', 'visible');
      return;
    }
    sectionEl.classList.add('reveal');
    const obs = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          sectionEl!.classList.add('visible');
          obs.disconnect();
        }
      },
      { threshold: 0.1 }
    );
    obs.observe(sectionEl);
    return () => obs.disconnect();
  });
</script>

<section class="cta" id="termin" aria-labelledby="cta-heading" bind:this={sectionEl}>
  <div class="glow" aria-hidden="true"></div>
  <div class="wrap">
    <p class="eyebrow">{effectiveEyebrow}</p>
    <h2 id="cta-heading">
      {effectiveTitle}
      {#if effectiveTitleEmphasis}
        {' '}<em>{effectiveTitleEmphasis}</em>
      {/if}
    </h2>
    <p class="subtitle">{effectiveSubtitle}</p>
    <div class="btn-row" role="group" aria-label={t(locale, 'cta.aria-group')}>
      <a href={primaryHref} class="btn btn-primary">
        {effectivePrimaryText}
        <svg viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
          <path d="M2 7h10M8 3l4 4-4 4"/>
        </svg>
      </a>
      {#if secondaryText && secondaryHref}
        <a href={secondaryHref} class="btn btn-ghost">{secondaryText}</a>
      {/if}
    </div>
  </div>
</section>

<style>
  .cta {
    padding: 130px 0;
    border-top: 1px solid var(--line);
    position: relative;
    overflow: hidden;
  }

  .glow {
    position: absolute;
    inset: 0;
    background: radial-gradient(ellipse at 50% 100%, oklch(0.80 0.09 75 / .22), transparent 75%);
    pointer-events: none;
  }

  .wrap {
    max-width: 760px;
    margin: 0 auto;
    padding: 0 40px;
    text-align: center;
    position: relative;
    z-index: 1;
  }

  .eyebrow {
    font-family: var(--mono);
    font-size: 11px;
    letter-spacing: 0.18em;
    text-transform: uppercase;
    color: var(--brass);
    display: inline-flex;
    align-items: center;
    gap: 10px;
    margin: 0 0 24px;
  }

  .eyebrow::before {
    content: "";
    width: 22px;
    height: 1px;
    background: currentColor;
    opacity: 0.8;
  }

  h2 {
    font-family: var(--serif);
    font-size: clamp(36px, 4.6vw, 60px);
    font-weight: 350;
    line-height: 1.1;
    letter-spacing: -0.02em;
    color: var(--fg);
    margin: 0;
  }

  h2 em {
    font-style: italic;
    font-weight: 400;
    color: var(--brass-2);
  }

  .subtitle {
    font-size: 18px;
    line-height: 1.6;
    color: var(--fg-soft);
    max-width: 54ch;
    margin: 20px auto 0;
  }

  .btn-row {
    display: flex;
    flex-wrap: wrap;
    gap: 14px;
    justify-content: center;
    margin-top: 36px;
  }

  .btn {
    display: inline-flex;
    align-items: center;
    gap: 10px;
    padding: 14px 22px;
    border-radius: 999px;
    font-family: var(--sans);
    font-size: 14px;
    font-weight: 600;
    text-decoration: none;
    transition: transform 0.2s ease, background 0.2s ease, border-color 0.2s ease, color 0.2s ease;
  }

  .btn svg {
    width: 14px;
    height: 14px;
  }

  .btn-primary {
    background: var(--brass);
    color: var(--ink-900);
  }

  .btn-primary:hover {
    background: var(--brass-2);
    transform: translateY(-1px);
    box-shadow: 0 0 28px oklch(0.80 0.09 75 / 0.45);
  }

  .btn-ghost {
    color: var(--fg);
    border: 1px solid var(--line-2);
    background: transparent;
  }

  .btn-ghost:hover {
    border-color: var(--brass);
    color: var(--brass);
  }

  @media (max-width: 640px) {
    .cta {
      padding: 80px 0;
    }

    .wrap {
      padding: 0 22px;
    }
  }
</style>
